---
rule-providers:
  DWD_Ads:
    type: http
    behavior: classical
    path: "./DWD_rule/DWD_Ads.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Ads.yaml
  DWD_Sosmed:
    type: http
    behavior: classical
    path: "./DWD_rule/DWD_Sosmed.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Sosmed.yaml
  DWD_Streaming:
    type: http
    behavior: classical
    path: "./DWD_rule/DWD_Streaming.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Streaming.yaml
  DWD_Gaming:
    type: http
    behavior: classical
    path: "./DWD_rule/DWD_Gaming.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Gaming.yaml
  DWD_Gaming_tcp:
    type: http
    behavior: classical
    path: "./DWD_rule/DWD_Gaming_tcp.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Gaming_tcp.yaml
  DWD_Gaming_udp:
    type: http
    behavior: classical
    path: "./DWD_rule/DWD_Gaming_udp.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Gaming_udp.yaml
  DWD_Akrab:
    type: http
    behavior: classical
    path: "./DWD_rule/DWD_Akrab.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Akrab.yaml
  DWD_Adguard:
    type: http
    behavior: domain
    path: "./DWD_rule/DWD_Adguard.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Adguard.yaml
  DWD_Traffic_Indo:
    type: http
    behavior: domain
    path: "./DWD_rule/DWD_Indo.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Traffic_Indo.yaml
  DWD_Speedtest:
    type: http
    behavior: domain
    path: "./DWD_rule/DWD_Speedtest.yaml"
    url: https://raw.githubusercontent.com/dwd93/DWD_rule/main/DWD_Speedtest.yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: DWD
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 8.8.8.8
  - 1.0.0.1
  - https://dns.google/dns-query
  fallback:
  - 1.1.1.1
  - 8.8.4.4
  - https://cloudflare-dns.com/dns-query
  - 112.215.203.254
  default-nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - 112.215.203.254
proxy-groups:
- name: UNIVERSAL
  type: select
  disable-udp: false
  proxies:
  - LOADBALANCE
  - BEST-PING
- name: GAME
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - LOADBALANCE
  - BEST-PING
- name: SOSMED
  type: select
  disable-udp: false
  proxies:
  - LOADBALANCE
  - BEST-PING
- name: STREAMING
  type: select
  disable-udp: false
  proxies:
  - LOADBALANCE
  - BEST-PING
- name: AKRAB
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - LOADBALANCE
  - BEST-PING
- name: ADBLOCK
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - LOADBALANCE
  - BEST-PING
- name: TRAFFIC INDO
  type: select
  disable-udp: false
  use:
  - VPN (1)
  - VPN (2)
- name: SPEEDTEST
  type: select
  disable-udp: false
  proxies:
  - LOADBALANCE
  - BEST-PING
  use:
  - VPN (1)
  - VPN (2)
- name: LOADBALANCE
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - VPN (1)
  - VPN (2)
  url: http://www.gstatic.com/generate_204
  interval: '10'
- name: BEST-PING
  type: url-test
  disable-udp: false
  use:
  - VPN (1)
  - VPN (2)
  url: http://www.gstatic.com/generate_204
  interval: '10'
  tolerance: '150'
rules:
- RULE-SET,DWD_Adguard,ADBLOCK
- RULE-SET,DWD_Ads,ADBLOCK
- RULE-SET,DWD_Akrab,AKRAB
- RULE-SET,DWD_Gaming,GAME
- RULE-SET,DWD_Gaming_tcp,GAME
- RULE-SET,DWD_Gaming_udp,GAME
- RULE-SET,DWD_Sosmed,SOSMED
- RULE-SET,DWD_Streaming,STREAMING
- RULE-SET,DWD_Traffic_Indo,TRAFFIC INDO
- RULE-SET,DWD_Speedtest,SPEEDTEST
- MATCH,GLOBAL
proxy-providers:
  VPN (1):
    type: file
    path: "./proxy_provider/vpn1.yaml"
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  VPN (2):
    type: file
    path: "./proxy_provider/vpn2.yaml"
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
