port: 7890
socks-port: 7891
#redir-port: 7892
mixed-port: 7893
#tproxy-port: 7895
mode: global
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret : ""
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7894
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - tls://1dot1dot1dot1.cloudflare-dns.com
  fallback:
    - https://dns.google/dns-query
proxy-providers:
  Vmess:
    type: file
    path: "./proxy_provider/vmess.yaml"
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  Trojan:
    type: file
    path: "./proxy_provider/trojan.yaml"
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
      
#Gunakan tanda pagar menghiden, jika salah satu server tidak kepakai
proxy-groups:
- name: UNIVERSAL
  type: select
  disable-udp: false
  proxies:
    - LOADBALANCE
    - BEST-PING
- name: AKRAB
  type: select
  disable-udp: false
  proxies:
    - DIRECT
    - LOADBALANCE
    - BEST-PING
  url: http://www.gstatic.com/generate_204
- name: LOADBALANCE
  type: load-balance
  strategy: round-robin
  disable-udp: false
  url: http://www.gstatic.com/generate_204
  interval: '300'
  use:
    - Vmess
    - Trojan 
- name: BEST-PING
  type: url-test
  disable-udp: false
  url: http://www.gstatic.com/generate_204
  interval: '300'
  tolerance: '50'
  use:
    - vmess
    - Trojan 
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  # > WHATSAPP,AKRAB
- DOMAIN-KEYWORD,whatsapp.com,AKRAB
- DOMAIN-KEYWORD,whatsapp.net,AKRAB
- DOMAIN-SUFFIX,g.whatsapp.net,AKRAB
- DOMAIN-SUFFIX,web.whatsapp.com,AKRAB
- DOMAIN-SUFFIX,scontent.whatsapp.net,AKRAB
- DOMAIN-SUFFIX,whatsapp.com,AKRAB
- DOMAIN-SUFFIX,static.whatsapp.net,AKRAB
- DOMAIN-SUFFIX,mmg.whatsapp.net,AKRAB
- DOMAIN-SUFFIX,media.fbdj2-1.fna.whatsapp.net,AKRAB
- DOMAIN-SUFFIX,media-xsp1-2.cdn.whatsapp.net,AKRAB
- DOMAIN,graph.facebook.com,AKRAB
- DOMAIN-SUFFIX,bintray.com,AKRAB
- DOMAIN-SUFFIX,whatsapp.biz,AKRAB
- DOMAIN-SUFFIX,whatsapp.com,AKRAB
- DOMAIN-KEYWORD,whatsapp,AKRAB
- IP-CIDR,108.168.174.0/16,AKRAB
- IP-CIDR,158.85.224.160/27,AKRAB
- IP-CIDR,158.85.46.128/27,AKRAB
- IP-CIDR,158.85.5.192/27,AKRAB
- IP-CIDR,173.192.222.160/27,AKRAB
- IP-CIDR,173.192.231.32/27,AKRAB
- IP-CIDR,174.37.243.0/16,AKRAB
- IP-CIDR,18.194.0.0/15,AKRAB
- IP-CIDR,184.173.128.0/17,AKRAB
- IP-CIDR,208.43.122.128/27,AKRAB
- IP-CIDR,34.224.0.0/12,AKRAB
- IP-CIDR,50.22.198.204/30,AKRAB
- IP-CIDR,54.242.0.0/15,AKRAB
- IP-CIDR,69.171.235.0/16,AKRAB
- IP-CIDR,75.126.150.0/16,AKRAB
- DST-PORT,5228,AKRAB
- DST-PORT,5222,AKRAB
- DST-PORT,38211,AKRAB

  # > MICROSOFT,AKRAB
- DOMAIN-SUFFIX,smartscreen-prod.microsoft.com,AKRAB
- DOMAIN-SUFFIX,self.events.data.microsoft.com,AKRAB
- DOMAIN-SUFFIX,nav.smartscreen.microsoft.com,AKRAB
- DOMAIN-SUFFIX,edge.microsoft.com,AKRAB
  
  # > RUANGGURU,AKRAB
- DOMAIN-SUFFIX,ruangguru.com,AKRAB
- DOMAIN-SUFFIX,belajar.ruangguru.com,AKRAB
- DOMAIN-SUFFIX,midtrans.com,AKRAB
- DOMAIN-SUFFIX,api.midtrans.com,AKRAB
  
  # > ZOOM,AKRAB
- DOMAIN-SUFFIX,zoom.us,AKRAB
- DOMAIN-SUFFIX,google.zoom.us,AKRAB
- DOMAIN-SUFFIX,us02st1.zoom.us,AKRAB
- DOMAIN-SUFFIX,us03st1.zoom.us,AKRAB
- DOMAIN-SUFFIX,us04st1.zoom.us,AKRAB
- DOMAIN-SUFFIX,us02st2.zoom.us,AKRAB
- DOMAIN-SUFFIX,us03st2.zoom.us,AKRAB
- DOMAIN-SUFFIX,us04st2.zoom.us,AKRAB
- DOMAIN-SUFFIX,us02st3.zoom.us,AKRAB
- DOMAIN-SUFFIX,us03st3.zoom.us,AKRAB
- DOMAIN-SUFFIX,us04st3.zoom.us,AKRAB
- DOMAIN-SUFFIX,us02web.zoom.us,AKRAB
- DOMAIN-SUFFIX,zoom.ada.support,AKRAB
- DOMAIN-SUFFIX,st1.zoom.us,AKRAB
- DOMAIN-SUFFIX,us02zpns.zoom.us,AKRAB
- DOMAIN-SUFFIX,us04xmppapi.zoom.us,AKRAB
- DOMAIN-SUFFIX,us04st1.zoom.us,AKRAB
- DOMAIN-SUFFIX,us04xmpp1.zoom.us,AKRAB
- DOMAIN-SUFFIX,xmpp013.zoom.us,AKRAB
- DOMAIN-SUFFIX,logfiles.zoom.us,AKRAB
- DOMAIN-SUFFIX,cdn.zoom.us,AKRAB
- DOMAIN-SUFFIX,zoom-general.s3.amazonaws.com,AKRAB
- DOMAIN-SUFFIX,zoomca193-123-14-89mmr.cloud.zoom.us,AKRAB
- DOMAIN-SUFFIX,zoomca193-123-1-56zc.cloud.zoom.us,AKRAB
- DST-PORT,8801,AKRAB
- DST-PORT,8802,AKRAB
- DST-PORT,3478,AKRAB
- DST-PORT,3479,AKRAB
 
  # > AREA KHUSUS XL AKRAB

  # > GOOGLE MEET, CLASSROOM, HANGOUTS, MAPS,AKRAB
- DOMAIN-SUFFIX,meetings.googleapis.com,AKRAB
- DOMAIN-SUFFIX,classroom.google.com,AKRAB
- DOMAIN-SUFFIX,hangouts.googleapis.com,AKRAB

  # MAPS,AKRAB
- DOMAIN-SUFFIX,userlocation.googleapis.com,AKRAB
- DOMAIN-SUFFIX,stun.l.google.com,AKRAB
- DOMAIN-SUFFIX,instantmessaging-pa.googleapis.com,AKRAB
- DOMAIN-SUFFIX,mtalk.google.com,AKRAB
- DOMAIN-SUFFIX,mobilemaps.googleapis.com,AKRAB
- DOMAIN-SUFFIX,mobilemaps-pa-gz.googleapis.com,AKRAB
- DOMAIN-SUFFIX,clients4.google.com,AKRAB
- DOMAIN-SUFFIX,android.googleapis.com,AKRAB
- DOMAIN-SUFFIX,safebrowsing.googleapis.com,AKRAB
- DOMAIN-SUFFIX,lh3.googleusercontent.com,AKRAB
- DOMAIN-SUFFIX,lh5.googleusercontent.com,AKRAB
- DOMAIN-SUFFIX,apis.google.com,AKRAB
- DOMAIN-SUFFIX,peoplestack-pa.googleapis.com,AKRAB
- DOMAIN-SUFFIX,gz0.googleusercontent.com,AKRAB
- DOMAIN-SUFFIX,geoar.googleapis.com,AKRAB
- DOMAIN-SUFFIX,streetviewpixels-pa.googleapis.com,AKRAB
- DOMAIN-SUFFIX,maps.gstatic.com,AKRAB
- DOMAIN-SUFFIX,maps.google.com,AKRAB
- DOMAIN-SUFFIX,optimizationguide-pa.googleapis.com,AKRAB

  # CLASSROOM,AKRAB
- DOMAIN-SUFFIX,dns.google,AKRAB
- DOMAIN-SUFFIX,clients3.google.com,AKRAB
- DOMAIN-SUFFIX,notifications-pa.googleapis.com,AKRAB
  # PORTS,AKRAB
- DST-PORT,19302,AKRAB
- DST-PORT,19305,AKRAB

  # > Microsoft Teams,AKRAB
- DOMAIN,teams.events.data.microsoft.com,AKRAB
- DOMAIN-SUFFIX,teams.cdn.live.net,AKRAB
- DOMAIN-SUFFIX,teams.live.com,AKRAB
- DOMAIN-SUFFIX,teams.microsoft.com,AKRAB

  # > Campuran,AKRAB
- DOMAIN-KEYWORD,zoom.us,AKRAB
- DOMAIN-KEYWORD,meet.google.com,AKRAB
- DOMAIN-KEYWORD,ruangguru.com,AKRAB
- DOMAIN-KEYWORD,zenius.com,AKRAB
- DOMAIN-KEYWORD,office.com,AKRAB
- DOMAIN-KEYWORD,trouter.io,AKRAB
- DOMAIN-KEYWORD,skype.com,AKRAB
- DOMAIN-KEYWORD,skype.net,AKRAB
- DOMAIN-KEYWORD,cortana.ai,AKRAB
- DOMAIN-KEYWORD,customspeech.ai,AKRAB
- DOMAIN-KEYWORD,bing.com,AKRAB
- DOMAIN-KEYWORD,microsoft.com,AKRAB
- DOMAIN-KEYWORD,hivestreaming.com,AKRAB
- DOMAIN-KEYWORD,kollective.app,AKRAB
- DOMAIN-KEYWORD,kollectivecd.com,AKRAB
- DOMAIN-KEYWORD,office365.us,AKRAB
- DOMAIN-KEYWORD,live.com,AKRAB
- DOMAIN-KEYWORD,svc.ms,AKRAB
- DOMAIN-KEYWORD,office.com,AKRAB
- DOMAIN-KEYWORD,officeppe.com,AKRAB
- MATCH,GLOBAL

